### ISSUE TITLE
Display List of Tags on Blog Home Page

### ISSUE THREAD

**Issue by aatmanvaidya** [tattle-made/website#122]
A list of all the tags used in blogs should be displayed on the blog home page (blog index page). 
so it should be like a sidebar which contains all the tags and the number of blog posts in each tag. 

Maybe in the future, we can add a feature that filters all the blog posts based on a user selecting multiple tags.

**Comment by dennyabrain** [comment]
@aatmanvaidya I know this will be tough, but can you do an investigation on what it takes to do more complex queries like, "get all posts by denny with the tag 'media-literacy' " ?

I think that this would be impossible to do via static pages because that would require creating static pages for ALL possible userXtag combination but should be doable on the client side. If we did something like generating a json which contained posts(just heading, author, description and url) with all userXtag combinations and use javascript to query it.
