### ISSUE TITLE
Create Contributor Page

### ISSUE THREAD

**Issue by tarunima** [tattle-made/website#14]
@dennyabrain  @tarunima

**Comment by dennyabrain** [comment]
hey @tarunima lets put together some references here?
so far i am thinking of two formats so far
1) https://allcontributors.org/
2) reusing the design saakshita made for us for the pitch deck

1 looks more automation friendly and less hassle of maintenance

**Comment by dennyabrain** [comment]
<img width="870" alt="Screen Shot 2020-06-05 at 3 31 57 PM" src="https://user-images.githubusercontent.com/1415361/83864036-d49d1a80-a741-11ea-9b88-2b7cbdd5cc04.png">
This separation between full timers and advisors was important for our pitch deck but might not be suitable for our website. I do like the idea of supporting both kinds of "team member" UI components.

1. Image, Name, Designation, Short Description
2. Name, Designation

because sometimes it might be hard/inconvenient to get all information about our teammates.

**Comment by dennyabrain** [comment]
@surajsharma 
some pointed instructions
create a new page at /contributors

and try to implement the design on my last comment with responsiveness in mind. the image attached shows how it looks on a laptop. you might have to imagine a graceful fallback for mobile devices. for laptops, its a 3 column layout. the upper row with the image thumbnails shows the main team members. and the bottom row is for consultants/contributors. you can use stock images for now. I dont have the actual images of team member.

look here for an example of how to load aand display local image using gatsby https://github.com/tattle-made/website/blob/master/src/components/atomic/ResponsiveImage.js

this componnent loads aand displays the files landing-page-wide.png and landing-page-narrow.png from the imaages folder

just create the page. Linking it from the homepage is not in scope for this issue.
