### ISSUE TITLE
Link blog to website

### ISSUE THREAD

**Issue by tarunima** [tattle-made/website#15]
@dennyabrain

**Comment by dennyabrain** [comment]
wheree do you prefer it to be? header, footer?
i think we should keep the header item counts under 5

could we also move the 2019 report to the footer?

**Comment by tarunima** [comment]
yes to 2019 report being in footer. blog can be in header

**Comment by dennyabrain** [comment]
aah ok. will do this.

just fyi, i think we should start a new issue on website navigation practices. because its going to be more of a long running discussion. 
I think website navigation has certain best practices
1) how many items to put in the header
2) what goes in the footer

i also have mild concerns. our squarespace analytics told us that faq was the second most clicked link. clearly people are interested in that, then shouldn't it be in the header. so yeah def in favour of making the act of "changing navigationn" a bit more thoughtful.

**Comment by dennyabrain** [comment]
I've addressed it here https://github.com/tattle-made/website/commit/1c5debf9fbcde80400a03268f4e6fcf2d172affa

Will start a new issue to discuss navigation best practices.

**Comment by tarunima** [comment]
closing this. website navigation convention needs to be decided but is independent of this issue.
