### ISSUE TITLE
Reducing space introduced by newline

### ISSUE THREAD

**Issue by tarunima** [tattle-made/website#2]
At the moment, the minimum space between two lines is quite high. 

See the spacing towards the end of 'About the Role': https://tattle.co.in/fullstack/

<img width="899" alt="Screen Shot 2020-05-04 at 7 13 47 PM" src="https://user-images.githubusercontent.com/13188366/80972413-b76fe600-8e3b-11ea-84df-e8a84aee32a4.png">

It would be better to reduce the minimum space between two lines. If more is needed people can click enter twice.

**Comment by dennyabrain** [comment]
<img width="682" alt="Screen Shot 2020-05-13 at 12 20 03 PM" src="https://user-images.githubusercontent.com/1415361/81780416-20c6b780-9514-11ea-877e-46a03f74f3ca.png">

@tarunima  do you like this?
It turns out that this is a markdown feature. if you dont want markdown to treat an 'enter' as a new line but just as a linebreak, you do that by leaving two spaces at the end of the previous line before hitting enter.

So in the example above you will write "Start Date : Immediately" then press space bar twice and then hit enter.

lmk if this addresses the issue.

**Comment by tarunima** [comment]
Seems good for now. Closing this. Thanks!
